import Link from "next/link";

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-12">
      <h2 className="text-xl font-semibold tracking-tight text-white">
        {title}
      </h2>
      <div className="mt-4 space-y-4 text-base leading-relaxed text-zinc-400">
        {children}
      </div>
    </section>
  );
}

function Tag({ children }: { children: React.ReactNode }) {
  return (
    <span className="rounded-full border border-zinc-800 px-2.5 py-1 text-xs text-zinc-300">
      {children}
    </span>
  );
}

function FeatureItem({
  label,
  description,
}: {
  label: string;
  description: string;
}) {
  return (
    <li>
      <span className="font-medium text-zinc-300">{label}:</span> {description}
    </li>
  );
}

export default function PayrollAccountingMapperProject() {
  return (
    <section className="py-16 md:py-20">
      <div className="max-w-3xl">
        <Link
          href="/projects"
          className="inline-flex items-center gap-2 text-sm text-zinc-400 transition hover:text-white"
        >
          <span aria-hidden>←</span>
          Back to Projects
        </Link>

        <div className="mt-6 flex flex-wrap items-center gap-2">
          <span className="rounded-full border border-zinc-800 bg-zinc-900/30 px-2.5 py-1 text-xs text-zinc-300">
            Private Case Study
          </span>
          <span className="rounded-full border border-zinc-800 bg-zinc-900/30 px-2.5 py-1 text-xs text-zinc-300">
            Accounting Automation
          </span>
          <span className="rounded-full border border-zinc-800 bg-zinc-900/30 px-2.5 py-1 text-xs text-zinc-300">
            Full-Stack Web App
          </span>
        </div>

        <h1 className="mt-6 text-3xl font-semibold tracking-tight text-white md:text-5xl">
          Payroll Accounting Mapper
        </h1>

        <p className="mt-5 text-base leading-relaxed text-zinc-400 md:text-lg">
          Full-stack web application that automates payroll accounting entry
          generation for multi-client accounting firms. Reads Excel payroll
          reports, resolves accounting mappings per company and cost center, and
          exports journal entries formatted for direct import into the
          accounting system.
        </p>

        <div className="mt-6 rounded-lg border border-zinc-800 bg-zinc-900/20 p-5">
          <p className="text-sm font-medium text-white">Outcome</p>
          <p className="mt-2 text-sm leading-relaxed text-zinc-400">
            A process that previously took{" "}
            <span className="font-medium text-zinc-300">
              hours per company in Excel
            </span>{" "}
            now completes in seconds — with full traceability of mapped and
            unmapped payroll events across the entire client portfolio.
          </p>
        </div>

        <div className="mt-6 flex flex-wrap gap-2">
          {[
            "Python 3.12",
            "FastAPI",
            "asyncpg",
            "PostgreSQL 17",
            "Next.js 15",
            "TypeScript",
            "React",
            "Docker",
            "PM2",
            "OpenVPN",
          ].map((tag) => (
            <Tag key={tag}>{tag}</Tag>
          ))}
        </div>

        <Section title="Context">
          <p>
            Accounting firms that manage payroll for multiple client companies
            receive monthly payroll reports — pay stubs, vacation provisions,
            and 13th salary provisions — in Excel format, generated by each
            client&apos;s HR system.
          </p>

          <p>
            For each payroll event (salary, overtime, social security, etc.),
            the firm must generate accounting journal entries with the correct
            debit and credit accounts. These mappings vary by company and cost
            center, following the accounting plan and business rules of each
            client.
          </p>

          <p>
            Before this system, the entire process was done manually in
            spreadsheets — once a month, for every client — relying on each
            analyst&apos;s implicit knowledge of each company&apos;s accounting
            rules.
          </p>
        </Section>

        <Section title="Problem">
          <p>The original manual workflow had several structural issues:</p>

          <ul className="list-disc space-y-2 pl-5">
            <li>
              <span className="text-zinc-300">Time-consuming:</span> hours per
              company, repeated monthly across the entire client portfolio
            </li>
            <li>
              <span className="text-zinc-300">Error-prone:</span> mapping
              decisions depended on individual analyst knowledge, not
              centralized rules
            </li>
            <li>
              <span className="text-zinc-300">No visibility:</span> no way to
              quickly identify which payroll events lacked a valid accounting
              mapping
            </li>
            <li>
              <span className="text-zinc-300">Fragmented knowledge:</span> rules
              scattered across spreadsheets and people, not centralized or
              auditable
            </li>
            <li>
              <span className="text-zinc-300">No compounding efficiency:</span>{" "}
              each month required the same full manual effort with no
              accumulated benefit
            </li>
          </ul>
        </Section>

        <Section title="Solution">
          <p>
            I designed and built a complete web application to replace the
            entire manual accounting mapping workflow:
          </p>

          <ul className="list-disc space-y-2 pl-5">
            <FeatureItem
              label="File parsing"
              description="Dynamic reading and normalization of payroll Excel reports — pay stubs, vacation provisions, and 13th salary provisions — handling format variations across different HR systems."
            />
            <FeatureItem
              label="Accounting resolution"
              description="Priority-based mapping engine that resolves journal entry debit/credit accounts per company and cost center, cascading from specific rules to economic group defaults to global fallbacks."
            />
            <FeatureItem
              label="Mapping management"
              description="Browser-based interface to register payroll events and their accounting mappings, grouped by company and economic group — no spreadsheets or developer access needed."
            />
            <FeatureItem
              label="Review interface"
              description="Pre-export review screen with visual indicators for unmapped events, allowing analysts to identify and fix gaps before generating the final output."
            />
            <FeatureItem
              label="FPA export"
              description="Consolidated FPA export by economic group, including GPS entries and General Summary, formatted for direct import into FPA-ELEVOR — removing the entire manual data-entry step."
            />
          </ul>
        </Section>

        <Section title="Architecture & Engineering Notes">
          <p>
            The system is structured as a decoupled full-stack application,
            deployed in a hybrid environment:
          </p>

          <ul className="list-disc space-y-2 pl-5">
            <FeatureItem
              label="Backend"
              description="Python 3.12 with FastAPI for async REST API. asyncpg for direct async PostgreSQL 17 access without ORM overhead, keeping query control explicit."
            />
            <FeatureItem
              label="Frontend"
              description="Next.js 15 with TypeScript and React, served as a static build from the Linux server."
            />
            <FeatureItem
              label="Database"
              description="PostgreSQL 17 running in the production Windows Server environment, accessed from the Linux app server via OpenVPN tunnel."
            />
            <FeatureItem
              label="Deployment"
              description="Linux server managing the FastAPI process with PM2 for process supervision and automatic restarts. Docker used during local development for environment consistency."
            />
            <FeatureItem
              label="Mapping resolution"
              description="Priority chain — company + cost center → economic group + cost center → global default — providing flexible overrides with safe fallbacks at each level."
            />
          </ul>
        </Section>

        <Section title="Key Features">
          <ul className="list-disc space-y-2 pl-5">
            <li>
              Dynamic parsing of multiple payroll Excel formats — pay stubs,
              vacation provisions, 13th salary provisions
            </li>
            <li>
              Multi-CNPJ company registration, grouped by economic group tags
            </li>
            <li>
              Cost center registration per company with mapping overrides by
              cost center
            </li>
            <li>Three-level priority mapping resolution engine</li>
            <li>
              Review screen with visual indicators for unresolved payroll events
              before export
            </li>
            <li>
              Consolidated FPA export with GPS and General Summary by economic
              group
            </li>
            <li>
              Full event and mapping management directly through the browser
              interface
            </li>
          </ul>
        </Section>

        <Section title="Impact">
          <ul className="list-disc space-y-2 pl-5">
            <li>
              Eliminated a process that previously took hours per company — now
              completed in seconds
            </li>
            <li>
              Full traceability: analysts see exactly which events are mapped
              and which are missing, for every company in the portfolio
            </li>
            <li>
              Accounting rules are centralized and reusable, not locked in
              individual spreadsheets or analyst knowledge
            </li>
            <li>
              Consistent, repeatable output every month with no accumulated
              manual effort
            </li>
            <li>
              FPA export formatted for direct import, removing a full manual
              data-entry step from the accounting workflow
            </li>
          </ul>
        </Section>

        <Section title="Confidentiality">
          <p className="text-sm text-zinc-500">
            This project is documented as a private case study. Source code,
            accounting mappings, business rules, client data, and internal
            configurations are not included due to company policies and
            confidentiality requirements.
          </p>
        </Section>
      </div>
    </section>
  );
}
